sudo: required
services:
  - docker

before_install:
  - docker build -t michaelzhu101/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true michaelzhu101/react-test npm test

after_success:
  - docker build -t michaelzhu101/multi-client ./client
  - docker build -t michaelzhu101/multi-nginx ./nginx
  - docker build -t michaelzhu101/multi-server ./server
  - docker build -t michaelzhu101/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push michaelzhu101/multi-client
  - docker push michaelzhu101/multi-nginx
  - docker push michaelzhu101/multi-server
  - docker push michaelzhu101/multi-worker
